### ISSUE TITLE
Implement Sigmoid, Cost, and Predict Functions in Logistic Regression

### ISSUE THREAD

**Issue by Gdsc-Cummins** [Google-Developer-Student-Club-CCOEW/AIML-2023-GDSC-CUMMINS-X-GDSC-MMCOE#11]
# Hacktoberfest Open Source Contribution - Issue Description

## Issue: Implement Sigmoid, Cost, and Predict Functions in Logistic Regression

**Description**:

We are looking for contributors to help us implement three essential functions for logistic regression: Sigmoid, Cost, and Predict. This is part of the Hacktoberfest open-source contribution event.

**Steps to Contribute**:

1. Visit the "Logistic Regression" folder in our AIML-2023-GDSC-CUMMINS-X-GDSC-MMCOE GitHub repository for reference code and more details on the implementation tasks.

2. In the "Logistic Regression" folder, you will find the reference code necessary to complete these functions.

3. Your task is to complete the following functions:
   - `sigmoid`: Implement the sigmoid function.
   - `cost`: Implement the cost function for logistic regression.
   - `predict`: Implement the prediction function.

4. Create a new branch in your forked repository, make your changes to the code, and submit a Pull Request to the "Logistic Regression" folder of the AIML-2023-GDSC-CUMMINS-X-GDSC-MMCOE GitHub repository.

5. Ensure that your contributions are eligible for Hacktoberfest by tagging the Hacktoberfest label in your Pull Request.

6. Please comment in the related issue to indicate that you are working on this task, and this will make it easier for us to track your contributions.

7. Follow any coding guidelines and instructions provided in the code files within the "Logistic Regression" folder.

We appreciate your contributions to complete these important functions for logistic regression. Thank you for participating in Hacktoberfest with AIML-2023-GDSC-CUMMINS-X-GDSC-MMCOE. Your efforts will benefit the entire community. Happy coding!

**Comment by ishan-nahid** [comment]
You can assign it to me.

**Comment by SarveshAtawane** [comment]
Can you assign it to me?

**Comment by parthsolanke** [comment]
@SarveshAtawane and @ishan-nahid I have assigned the issue to both, please go ahead and start contributing

**Comment by SarveshAtawane** [comment]
@parthsolanke I am not a student of your institute would you accept my pr.

**Comment by parthsolanke** [comment]
what we will do that we wont be assigning this issue to any one just fork the repo and make your pr

**Comment by SarveshAtawane** [comment]
Ok @parthsolanke then I have made the PR.

**Comment by parthsolanke** [comment]
@SarveshAtawane your PR has been merged

**Comment by SarveshAtawane** [comment]
> @SarveshAtawane your PR has been merged

Was it not under hactober fest?
